### ISSUE TITLE
Error: No provider for ***!

### ISSUE THREAD

**Issue by smnbbrv** [troyanskiy/ngx-resource#102]
Hi @troyanskiy 

Just spent a couple of hours with a weird bug... angular-cli@1.0.0, latest versions of angular / ngx-resource-rest

> Error: No provider for e!

```ts
// app.module.ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { ResourceModule } from 'ngx-resource-rest';
import { PublicModule } from './public/public.module';
import { AppComponent } from './app.component';
// import { PublicResource } from './public/public.resource';

// console.log(PublicResource);

@NgModule({
  declarations: [ AppComponent ],
  imports: [
    BrowserModule,
    HttpModule,
    ResourceModule.forRoot(),
    RouterModule.forRoot([
      { path: '', redirectTo: '/registration', pathMatch: 'full' },
    ]),

    PublicModule,
  ],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
```

There is no error on a normal dev server mode or even on a standard build. However, on a -prod build it stops working with the error above.

The simplest resource and the simplest component where it gets injected. I tried everything: moving imports around, triple checking for circular dependencies, etc.

The only thing that helps is uncommenting those two lines 

```ts
// import { PublicResource } from './public/public.resource';

// console.log(PublicResource);
```

it enforces the resource file to be loaded before `ResourceModule.forRoot(),` call and `console.log` prevents it from being destroyed by the tree shaking.

I assume something goes wrong with the module loading, probably the files get loaded lazily; for some reason the decorator is not called before actual `forRoot`.

Are there ways to fix this? Is there any way to work this around? Could the Resource instances be registered as normal providers without `forRoot` call / without importing `ResourceModule` at all?

**Comment by troyanskiy** [comment]
Hello @smnbbrv 
I think you have wrong import.
It should be `import { ResourceModule } from 'ngx-resource';`

**Comment by smnbbrv** [comment]
Hi @troyanskiy 

thanks for the point; yes, it was wrong, I tried it first with ng2-resource-rest, did not work, so I replaced it with this but seems like did not test.

Still the same problem after replaced it.

**Comment by smnbbrv** [comment]
registering the provider manually works fine. 

```ts
// module
providers: [
  PublicResource
],

// resource
@ResourceParams({ url: '...' })
export class PublicResource extends Resource {

  constructor(http: Http) {
    super(http, null);
  }

  // ..

}
```

and I even like it way more because it feels "more angular".

The only thing which is ugly is of course `constructor` (cannot resolve parameters blabla if it is not specified) which is I guess the reason why you do it automatically.

Is it like that or do I miss something?

**Comment by smnbbrv** [comment]
this could be fixed on my side by simple 

```ts
import { Injectable } from '@angular/core';
import { Resource } from 'ngx-resource';
import { Http } from '@angular/http';

@Injectable()
export class BaseResource extends Resource {

  constructor(http: Http) {
    super(http, null);
  }

}
```

and extending it later, so I am very sure it can be fixed by adding `Injectable` to `Resource` class.

See https://github.com/troyanskiy/ng2-resource-rest/pull/103

**Comment by troyanskiy** [comment]
Did you decorate all your resources with `@Injectable()`?
You need to decorate all final resources with `@Injectable()` decorator. In fact the resource is an a service/provider.

**Comment by troyanskiy** [comment]
Here is your example
```typescript
@Injectable()
@ResourceParams({ url: '...' })
export class PublicResource extends Resource {

}
```

**Comment by smnbbrv** [comment]
hi @troyanskiy 

usually I don't and it works. `Injectable` makes sense only if there are some parameters in the `constructor` function that need to be injected.

If I want to register the resource as a provider manually, base Resource class should have Injectable in this case because it is the one that has a constructor with two (at least) injectable parameters. The leaf resource's Injectable is just kinda useless in 99% of the cases because usually you don't have a constructor on a leaf resource.

I tried adding Injectable to this particular `PublicResource` and it did not solve the problem. So the only thing that really works fine for me is providing the resource in a normal way https://github.com/troyanskiy/ng2-resource-rest/issues/102#issuecomment-296240749 and extending this base class in order to resolve the injected services https://github.com/troyanskiy/ng2-resource-rest/issues/102#issuecomment-296246521 (and it works even without Injectable on the `PublicResource`).

This is just my observation. I don't pretend to be the one who is right, I just want to solve my problem. It is of course your business to close a pull request, however the proposed change was not breaking for anybody, only adding some more functionality.

I actually believe that there should be a clear way how to use normal module providers because the current magical way is too unclear, in fact it implements another dependency injection (which is I believe too much for a simple library) and another modules concept while angular already has built-in both; I am not even able to debug the things how they happen here (most of the users won't even try). The injected Injector in this particular case is also not a good practice and is not recommended by angular team. Also, from my experience, the magical way is too unstable, from time to time I have problems with its loading order etc in big projects and especially with AOT, uglify and tree shaking, and this issue is one more in the list.

So, coming to the global thing: I think there should be the way to use normal `providers` and normal `NgModule`, at least as an alternative.

I think I already found a solution for me, but the issue, I think, is not solved.

**Comment by smnbbrv** [comment]
ah yes, if I register the providers on my own, I don't need any of `ResourceModule.forRoot()` (replaced by `providers`) or `ResourceModule.forChild()` (replaced by `NgModule`)

**Comment by troyanskiy** [comment]
Yes. I agree with you.
I did not really play with AOT but I think in AOT case you will have to skip that "magical" way of creating resources with `ResourceModule.forRoot()` or `ResourceModule.forChild()`.
And it's better to add the resources classes by hand into providers list.

I also agree with you about the `Injector`, I will simplify it.

**Comment by smnbbrv** [comment]
Thanks! Just let me know if I can help somehow...

**Comment by vaidd4** [comment]
Hi, I'm getting the same problem only after aot building. But I dont get working the workaround.
As mentioned above, I have an central resource with a constructor and added to the `providers` that is extended by all other resources

I'm using ResourceCRUDBase

```TYPESCRIPT
// AppModule
  providers: [
    // ...
    BaseResource
  ],

// BaseResource
@ResourceParams({
  url: 'https://api.mysite.com/',
})
export class BaseResource<TQuery, TKeys, TShort, TFull> extends ResourceCRUDBase<TQuery, TKeys, TShort, TFull> {
  constructor(http: Http) {
    super(http);
  }
  // ...
}

// UsersResource extending BaseResource
@Injectable()
@ResourceParams({
  path: 'users/{id}'
})
export class UsersResource extends BaseResource<any, any, any, any> {
}

```
Having or not `Injectable` or the `constructor` on BaseRessource doesn't change anything.

**The only thing working is adding every resources to `providers`.**

**Comment by smnbbrv** [comment]
The only way to deal with AOT is adding every resource to providers manually, which is actually not a workaround but quite a valid behavior... And you should have Injectable decorator on the resources with explicit constructor. Only this combination works fine for me

**Comment by vaidd4** [comment]
@smnbbrv I'm agree on the behavior, it's just that the others workarounds didn't worked for me.

And I've modified my `BaseResource` multiple times now I've just `Injectable` and no `constructor`.

**Comment by troyanskiy** [comment]
Hello all.

I've released some kind of beta of new library which is called `rest-core` + `rest-ngx`.
Please check them [`rest-core`](https://www.npmjs.com/package/rest-core) and [`rest-ngx`](https://www.npmjs.com/package/rest-ngx).

It works the way like `ngx-resource` but has a lot of breaking changes.
Something was removed or simplified.

I've migrated all my projects to the new library.
If you wish to switch to HttpClient or use some other http handlers like `fetch` try to migrate your projects to the lib.

Bugs and help requests are welcome in corresponding repos.

Thanks!

PS: Since `ngx-resource` is no longer supported by me, closing the issue.

**Comment by smnbbrv** [comment]
Hi @troyanskiy will definitely check this out! Keep rocking!
