### ISSUE TITLE
Add metadatas to output

### ISSUE THREAD

**Issue by jeremypele** [troyanskiy/ngx-resource#105]
Hi,

I'm thinking about a way to augment my result collection with metadatas (pagination for instance). 
I already seen some posts dealing with this, but feels a bit tricky everytime. 
I think there should be a way to factorize this and not write custom `responseInterceptor` for each endpoint that needs response to be augmented with pagination metadatas.

I have a `RestResource` class that extends `Resource` and a global `responseInterceptor`,
I'm defining a property `metadatas` on my response
```
(response: Response) => {
 let improvedResponse = (<any>response)._body ? ResourceHelper.camelize(response.json()) : null

 Object.defineProperty(improvedResponse, 'metadatas', {
   value: this.buildPagination(response.headers)
 });
 subscriber.next(improvedResponse)
},
```
This would require `ResourceAction` to be modified this way (lines 257 -> 270)

```
var metadatas = resp.metadatas
resp = resp.filter(filter).map(map);
resp = !!resourceModel ? mapToModel.bind(_this)(resp, resourceModel) : resp;

Object.defineProperty(resp, 'metadatas', { value: metadatas });

Array.prototype.push.apply(ret, resp);
```
It would help in a lot of cases IMO

I'm more than willing to write a P.R for this case, just wanna be sure that I'm facing the right way to do it before spending time on it.

**Comment by troyanskiy** [comment]
Hi!
Sorry for the delay.
May be you can you ResourceModel.
I would create generic class based on (extended) ResoureModel to handle pagination lists.

**Comment by jeremypele** [comment]
Thanks, I'll look into that direction
