### ISSUE TITLE
The 'cleanDataField' array is being sent in the request.

### ISSUE THREAD

**Issue by JulioWar** [troyanskiy/ngx-resource#108]
When I use the function `$save` with a ResourceModel. the request include the `cleanDataField` array.
![capture_network](https://cloud.githubusercontent.com/assets/6256473/25786787/dbe80fc2-3357-11e7-8e0e-5b4b70ffb290.PNG)

**Comment by troyanskiy** [comment]
Thank you for the issue. Could you please update the lib and test that on your side?
Thank you!

**Comment by JulioWar** [comment]
Perfect @troyanskiy , Thanks!
