### ISSUE TITLE
CleanData doesn't work

### ISSUE THREAD

**Issue by anfluff** [troyanskiy/ngx-resource#110]
Hello!
I haven't update for a long time but yesterday i did. 
Immediately i got tons of errors on all pages because all data, recieved from api by resources, got some extra fields like ($resolved, $resource, ... ).
I found short info about cleanData function in last updates but i cant understand should i configure it somehow? or maybe enable it?

**Comment by troyanskiy** [comment]
Hello.
Yes, now all data is extended with resource info.
I will add some extra flag to get result without resource data.

**Comment by troyanskiy** [comment]
Hello @anfluff, @niveo and @vaidd4 
I'm implementing that extra flag now and would like to clarify some details from you.
Did you receive that extra fields like ($resolved, $resouce...) on front end part of backend part?
It will be great to have some examples from you.
Thank you.

**Comment by anfluff** [comment]
It's my query request. Im getting array of 2 items: first is array of objects, second is pagination data. 
Whole array turns to objects coz its getting some "$.." elements, and each of array items getting "resourse" element.

![My array](https://pp.userapi.com/c836534/v836534676/453d6/4PqofRBtOEI.jpg)

**Comment by troyanskiy** [comment]
Hello @anfluff, @niveo and @vaidd4

Please update to version 3.0.0.
Please note that there are breaking changes in the release. Please check change log for some details.
