### ISSUE TITLE
import only required parts from rxjs instead of rxjs/Rx

### ISSUE THREAD

**Issue by smnbbrv** [troyanskiy/ngx-resource#111]
Hi @troyanskiy 

is there any intention behind `import { Observable } from 'rxjs/Rx';` https://github.com/troyanskiy/ngx-resource/blob/master/src/Resource.ts#L3 instead of `import { Observable } from 'rxjs/Observable';`? This is of course comfortable because it sets up all the observable operators; however it makes the bundle size bigger.

Do you have plans on changing this?

**Comment by troyanskiy** [comment]
Hello @smnbbrv 
That is true, I will change it in next release.
Thanks a lot.

**Comment by smnbbrv** [comment]
Hi @troyanskiy 

this could be a breaking change for lots of people... Another major version?

**Comment by troyanskiy** [comment]
Why do you think so?
I will import only needed for the resource lib and if others will need some more from Rx, they should import it on theres project

**Comment by smnbbrv** [comment]
I did not import any of the operators before and today recognized why it actually was like that (so this is how this issue appeared). If this behavior will change, the library can't be updated safely anymore because there is a high chance that nobody actually imported any operators because they were just available until the update. That's why I think it can be breaking change, although it's fully library consumers' fault and not library's itself

**Comment by troyanskiy** [comment]
Actually... I've just replaced rxjs/Rx to more precise imports and the final bundle file become even bigger...
Before 131kb after 134kb.

**Comment by smnbbrv** [comment]
LOL, that can't really be it. Something should be wrong...

**Comment by smnbbrv** [comment]
could be that some of the `rxjs/Rx` imports is forgotten...

**Comment by troyanskiy** [comment]
LOL, Nope, RX is not included into the final bundle...

**Comment by troyanskiy** [comment]
Check the bundle file.
So I think I will keep the lib as is.

**Comment by troyanskiy** [comment]
Well... I think I will release that changes and mark as breaking changes.
It's better to precise imports.

**Comment by smnbbrv** [comment]
I'm a bit confused now, would you release those or not? :)

**Comment by troyanskiy** [comment]
Yes, I will. :)
