### ISSUE TITLE
Cannot inject custom provider to Resource after updating to 2.1.0

### ISSUE THREAD

**Issue by desfero** [troyanskiy/ngx-resource#112]
Hello, 
after upgrading to **2.1.0** `Injector` was removed from `Resource` class, but i used it for injecting my custom dependency do an `AuthResource`.

```
export class AuthResource extends Resource {
  constructor(http: Http,
              injector: Injector) {
    super(http, injector);

    const headersService = injector.get(HeadersService);
    // ...
  }
``` 

do we have any options to get same functionality after this change?

**Comment by troyanskiy** [comment]
Hello.
Yes, the Injector has been removed from Resource.

Please try to do like that 
```ts
@ResourceParams({
...
add2Provides: false
})
export class AuthResource extends Resource {
  constructor(http: Http,
              private headersService: HeadersService) {
    super(http);

    // ...
  }
```

Add the resource class to your app providers list.

**Comment by desfero** [comment]
After some diggings with this problem i remove import (ResourceModule) from my application and inject all resources by myself (fixing also aot issue with this approach)
