### ISSUE TITLE
How to handle multi pages resource and caching them?

### ISSUE THREAD

**Issue by namlehong** [troyanskiy/ngx-resource#114]
This is 2 questions, 

1. How to handle multi pages resource in the elegant way? And what is the correct way to update queried collection (eg: delete 1 item, create new item, update item to change current order..)

2. How to cache the result (even after delete/create) to reuse (of course with the cache technique come with force refresh methods) cause almost data not change when we browse between pages?

**Comment by troyanskiy** [comment]
This is more general questions which not related to the library.
Answering on first question I would say it depends on your backend. If you are developing the backend part I would say that it's better to have API
`GET` `/api/path/collection` will return list of items
`POST` `/api/path/collection` create item
`GET` `/api/path/collection/{itemId}` will return one item
`DELETE` `/api/path/collection/{itemId}` deletes item
`PUT` `/api/path/collection/{itemId}` will update
To list request you can add some params like sorting, paginating....

On second question I think you can google the answer.

**Comment by namlehong** [comment]
I also found some way to work by myself, just curious to find a correct/official way to work with library.
