### ISSUE TITLE
After upgrading to ngx-resource 3.0.0 query params are not added to url

### ISSUE THREAD

**Issue by desfero** [troyanskiy/ngx-resource#116]
as in title. Query params are not added to url.

Maybe somethinng wrong happen here:
```javascript
Resource.prototype.$_resolveMainOptions = function (shell) {
        // shell.data contains passed object to resource action (customersResource.query({ ... })
        return Promise
            .all([
            Promise.resolve(shell.options.url || this.$getUrl(shell.options)),
            Promise.resolve(shell.options.path || this.$getPath(shell.options)),
            Promise.resolve(shell.options.headers || this.$getHeaders(shell.options)),
            Promise.resolve(shell.options.params || this.$getParams(shell.options)),
            Promise.resolve(shell.options.data || this.$getData(shell.options))
        ])
            .then(function (data) {
            return {
                url: data[0],
                path: data[1],
                headers: new Headers(data[2] ? Object.assign({}, data[2]) : data[2]),
                params: data[3] ? Object.assign({}, data[3]) : data[3],
                data: data[4] ? Object.assign({}, data[4]) : data[4]
            };
        });
    };
```

**Comment by cipchk** [comment]
# +1 +1

**Comment by niuba** [comment]
+1+1

**Comment by OwlLaboratory** [comment]
+1 !

**Comment by desfero** [comment]
@troyanskiy is there any updates about this bug?

**Comment by troyanskiy** [comment]
Hello. Do you have any details?
I can't reproduce that on my project.

Could you please provide some code example of resource and how you call it?

Thank you.

**Comment by desfero** [comment]
@troyanskiy currently i'm out of my computer, but you can look at #118

**Comment by troyanskiy** [comment]
Hello again to all.
Could you please tell me your angular version?
I think it's related to angular 2 only, since they (angular developers) deprecates `search` param on request options I switched to `params` param.

File: https://github.com/angular/angular/blob/master/packages/http/src/interfaces.ts#L48-L58
```ts
export interface RequestOptionsArgs {
    url?: string;
    method?: string | RequestMethod;
    /** @deprecated from 4.0.0. Use params instead. */
    search?: string | URLSearchParams | {
        [key: string]: any | any[];
    };
    params?: string | URLSearchParams | {
        [key: string]: any | any[];
    };
    headers?: Headers;
    body?: any;
    withCredentials?: boolean;
    responseType?: ResponseContentType;
}
```
  
Thank you.

**Comment by troyanskiy** [comment]
So please test updated version `v3.0.1`.
Also please reply here what version of angular do you have with the bug.
If you have angular 2, please test it with parameter `angularV2: true` on `ResourceParams`

Ex:
```ts
@Injectable()
@ResourceParams({
  url: 'https://api.github.com/user',
  angularV2: true
})
export class GitHubUserService extends Resource {
  @ResourceAction({
    isArray: true,
    path: '/repos'
  })
  getRepos: ResourceMethod<IQueryInput, any[]>;
}
```

**Comment by desfero** [comment]
@troyanskiy i have this bug on latest angular (from 4 line). Let me check tommorrow if it is working

**Comment by troyanskiy** [comment]
So that is strange. I can't reproduce it.
Will be nice to have some project what I can easy `npm i`  and start to test the issue.

**Comment by niuba** [comment]
@troyanskiy i have this bug on angular4.0.0,the  `shell.options.data` || this.$getData(shell.options)` always be ""

**Comment by siovene** [comment]
`3.0.2` doesn't fix it for me. I run angular `4.1.3`.

**Comment by troyanskiy** [comment]
Thank you for the replies.
As I said above I can't reproduce that on my projects, so I will be nice to have some small project which I can easily start to debug.
Thank you.

**Comment by cipchk** [comment]
see [plunker](http://plnkr.co/edit/XVwBXIkDd9cjJyVq2UDH)

should be request url '/user?ps=10', but only '/user'.

**Comment by troyanskiy** [comment]
@cipchk Thank you. I will check it today.

**Comment by troyanskiy** [comment]
Voilà! It's fixed!

**Comment by desfero** [comment]
Works, thanks a lot
