### ISSUE TITLE
Testing services based on ngx-resource

### ISSUE THREAD

**Issue by tobias--** [troyanskiy/ngx-resource#117]
Is there any documentation on how to fake/mock services to test components or services that depend on providers that extend ngx-resources' Resource?

**Comment by desfero** [comment]
@tobias-- i prefer to create a jasmine spy.

```typescript
const spy = createSpyObj('CustomersResource', ['get']);

// provide it as a dependency for tested service/component
// and in test
spy.get.and.return({ $observable: of({ id: 'foo', name: 'bar' })})

```

**Comment by troyanskiy** [comment]
Hello
You can try to test with Http service mocking.
In fact resource === service (provider), so I believe you try this https://kendaleiv.com/angular-2-mockbackend-service-testing-template-using-testbed/

**Comment by troyanskiy** [comment]
Feel free to reopen the issue if you still have the question open.
