### ISSUE TITLE
Regression from 2.1.1 to 3.0.3: $getUrl (previously getUrl) not called

### ISSUE THREAD

**Issue by siovene** [troyanskiy/ngx-resource#119]
The following code used to work for me with `2.1.1`:

```typescript
export class RestClient extends Resource {
    private token: string = null;

    public setToken(token: string) {
        this.token = token;
    }

    public getUrl(methodOptions?: any): string | Promise<string> {
        let resPath = super.getUrl();
        return 'https://api.github.com' + resPath;
    }

    public getHeaders(methodOptions?: any): any {
        let headers = super.getHeaders();
        headers.Authorization = 'token ' + this.token;
        return headers;
    }
}

export interface IQueryInput {
  page?: number;
  perPage?: number;
}

@Injectable()
@ResourceParams({ url: '/user' })
export class GitHubUserService extends RestClient {
  @ResourceAction({ path: '/' })
  getUser: ResourceMethod<IQueryInput, any>;

  @ResourceAction({ isArray: true, path: '/repos' })
  getRepos: ResourceMethod<IQueryInput, any[]>;
}
```

`getUrl()` would be called and requests would be correctly issued to `https://api.github.com/user/` for `getUser()`, and `https://api.github.com/user/repos` for `getRepos()`.

After upgrading to `3.0.3` and changing `getUrl -> $getUrl` and `getHeaders -> $getHeaders`, the `$getUrl` function is never called, and the result is that API requests are issued to `http://localhost:8000/user`.

Note that `$getHeaders` works fine instead.

**Comment by ShayHaluba** [comment]
I Have the same problem, there is any progress?

Thanks.

**Comment by troyanskiy** [comment]
Thanks for the issue...
For now I do not have much time. I will check all ASAP.

Thanks.

**Comment by ShayHaluba** [comment]
Hi, 

I have looked at the code a little bit, and I think I found the problematic code.

if I wouldn't define the URL in the @ResourceParams decorator, the $getUrl() will be called.

for example :
@ResourceParams({
    **url: '/me', ---> if i delete this line the function will be called**
    angularV2: true
})

The lines of code in that responsible for that behavior are:
 Resource.prototype.$_resolveMainOptions = function (shell) {
        debugger;
        return Promise
            .all([
            **Promise.resolve(shell.options.url || this.$getUrl(shell.options)),**
            Promise.resolve(shell.options.path || this.$getPath(shell.options)),
         . . . . . 

I would be glad to hear your opinion about that.

Thanks :+1:

**Comment by siovene** [comment]
I think the current behaviour is fine, so long as the API break gets documented :-)

**Comment by troyanskiy** [comment]
Hello @siovene, @ShayHaluba 
As @siovene said the behaviour is correct.
If you define `url` in the `ResourceParams` or/and `ResourceAction` then $getUrl will never be called.

**Comment by troyanskiy** [comment]
Sorry for the delay, I had really tough dead line at work.

**Comment by mlaffargue** [comment]
I used to override `getUrl` to offer an API library that project could easily use by giving the URL prefix.
From your comments I moved the code to the $resourceAction method : 
```
  $resourceAction(data: any, params: any, callback: () => any, methodOptions: ResourceActionBase): ResourceResult<any> | ResourceModel<Resource> {
    if (this.prefix) {
      methodOptions.url = this.prefix + methodOptions.url;
    }

    return super.$resourceAction(data,params,callback, methodOptions);
  }
```
I think using `ResourceGlobalConfig` isn't an option as ngx-resource will be used to also call other servers (so different prefixes) from the same project.

**Comment by rcuddy** [comment]
I was also doing the same as @mlaffargue using getUrl to modify the url so it could go to different APIs based on which resource it was.

Thanks for that $resourceAction hack; I can go home now!
