### ISSUE TITLE
Map data into property of type Map<string, T> 

### ISSUE THREAD

**Issue by tobias--** [troyanskiy/ngx-resource#120]
It does not seem to be possible to use Map<string, X> as a property to be mapped into. 

Example:
```
export interface Schema {
  name: string;
  id: string;
  properties: Map<string, Property>;
}

export interface Property {
  id?: string;
  name?: string;
  title?: string;
}
```

Using the interfaces above, properties is a plain object and does not provide any methods a Map normally would, e.g. `.forEach` is not available. Is mapping/instantiating the correct type even possible?

**Comment by troyanskiy** [comment]
Hello.
I that case you should map data manually by overriding map method on the resource or defining it on ResourceAction.
Could you please show me your resource class so it will be more clear for me.

Thank you.

**Comment by troyanskiy** [comment]
Fill free to reopen the issue if you still have the question open.
