### ISSUE TITLE
Array is being converted to object in request body

### ISSUE THREAD

**Issue by tarvainen** [troyanskiy/ngx-resource#121]
Hello,

I would like to send array of data to my backend. Unfortunately the ngx-resource seems to convert this array structure to object with keys 0, 1, 2... and so on.

For example with the configuration and usage below:

```
@ResourceAction({
  path: '',
  method: RequestMethod.Post
})
save: ResourceMethod<string[], any>;

...

constructor(private myResource: MyResource) {
  this.myResource.save(['cat', 'dog', 'squirrel']);
}
```
the actual data is sent as `{0: "cat", 1: "dog", 2: "squirrel"}` which causes my backend to flip. I think this has something to do with the Resource.$cleanData since it puts looped values always back to the object even if the input would be an array.

Is this just a bug or have I totally missed some config?

**Comment by troyanskiy** [comment]
Thank you for the issue.
It's fixed, please update to 3.0.5

**Comment by jakubmank** [comment]
Hey I still experience the issue. 
`@ResourceAction({
    method: RequestMethod.Post,
  })
  saveCows: ResourceMethod<string[], Array<{eid, cow_id}>>;`

and that's how it looks: 
<img width="221" alt="screen shot 2017-07-26 at 09 06 20" src="https://user-images.githubusercontent.com/9478634/28622540-d4a32cf0-71e2-11e7-972c-6ca82a490dfc.png">
FYI I am using: 
Angular 4 
ngx-resource: 3.2.1

**Comment by troyanskiy** [comment]
@jakubmank As I can see you have an array of strings in the request payload. What is the problem?

**Comment by jakubmank** [comment]
Sorry, long day for me... it is working as supposed to. Thanks for quick response and sorry for bugging u.

**Comment by troyanskiy** [comment]
Not a problem. Have a great day/evening/night...

**Comment by jakubmank** [comment]
@troyanskiy  Hey unfortunately the latest update to 3.2.4 break this fix for sending object instead of array.

**Comment by troyanskiy** [comment]
Fixed. Please update to 3.2.5
