### ISSUE TITLE
Possible to receive an array of string (primitive)?

### ISSUE THREAD

**Issue by mlaffargue** [troyanskiy/ngx-resource#122]
It worked in 2.X but won't now.
The webservice I call send back an simple array of String.

I defined the resource as : 
```
  @ResourceAction({
    isArray: true,
    path: '/challenge'
  })
  challenge: ResourceMethod<void, string[]>;
```

Then I simply call with : 
```
this.apiService.getChallenge().$observable.subscribe(
      (data: Array<String>) => {
```

It crashes in `Resource.prototype.$_createMainObservable` when trying to add `$resource` to the first string of the array:
```
(_a = shell.returnExternal).push.apply(_a, resp
                                .filter(filter)
                                .map(map)
                                .map(function (respItem) {
                                if (!shell.options.lean) {
                                    respItem.$resource = _this; <-- HERE
                                }
                                return _this.$_setDataToObject(_this.$_initResultObject(shell.options), respItem);
                            }));
```

I tried to put `lean`to true but then I $observable is undefined.
Modifying the backend is not really an option, should I put a responseInterceptor to transform my string to objects ?

Thanks.

**Comment by mlaffargue** [comment]
I can't find if I introduced a Typo or if this just worked before. Well even precising the result is an array of `String` (object) they'll be treated as primitive and methods can't be added.

I added a "map" on this one to have objects : 
`map: (item)=>{return new String(item)}`

**Comment by troyanskiy** [comment]
Hello.
Thank you for the issue.
If fact it's a bug, which I just did fix it.
Please update to the latest version.
