### ISSUE TITLE
Inconsistency between `$observable` and `$observable.toPromise()`

### ISSUE THREAD

**Issue by marshall007** [troyanskiy/ngx-resource#129]
I would expect the following two examples to be equivalent, but it seems that when using `toPromise`, the result is still a wrapped `ResourceResult`:

```ts
resource.get({ id: '123' }).$observable.subscribe(
  (value) => this.data = value // T
)

resource.get({ id: '123' }).$observable.toPromise().then(
  (value) => this.data = value // ResourceResult<T>
)
```

**Comment by marshall007** [comment]
Somewhat related, there appears to be a possible race condition when using `resource.save(...)` which prevents `$cleanData(...)` from being called before the request is sent.

**Comment by troyanskiy** [comment]
For me both are same
```typescript
this._u.testGet()
      .$observable
      .subscribe((data: any) => {
        console.log('Data 1', data);
      });

    this._u.testGet()
      .$observable
      .toPromise()
      .then((data: any) => {
        console.log('Data 2', data);
      });
```

![image](https://user-images.githubusercontent.com/1538862/28440417-787b4eca-6da6-11e7-8096-292b6a5ff474.png)

**Comment by troyanskiy** [comment]
Could you please provide plunker example to the Inconsistency between `$observable` and `$observable.toPromise()`

Thanks

**Comment by marshall007** [comment]
@troyanskiy not sure what was going on before, but I can't reproduce this again. Also updating to `v3.2.4` seems to have fixed `$` properties being included in `POST` requests.
