### ISSUE TITLE
Body serialization

### ISSUE THREAD

**Issue by kptLucek** [troyanskiy/ngx-resource#131]
Hi

Is there any chance to change way, that body is being serialized?

Right now it's made by `JSON.stringify`, but... it resuts in many problems with backend API im using for that project.

The perfect way for me, would be to choose between `stringify` and for example `URLSearchParams` (aka, NG1 $httpParamSerializer) described in [here](https://stackoverflow.com/a/39859149).

If it's not possible to implement any soon, then any workaround more than welcome.

**Comment by troyanskiy** [comment]
Hello!
Thanks for the issue.
I've just implemented that for you. Published 3.3.0

1. You can overwrite `Resource` method `$bodySerializer(body: any): string` to implement customs serializer.
1. Or you can define if with `ResourceAction` decorator `bodySerializer(body: any): string` to implement custom serializer per resource method.

**Comment by kptLucek** [comment]
Works like a charm!

**Comment by troyanskiy** [comment]
I'm glad to hear that.
