### ISSUE TITLE
Initialize Resource without HTTP call?

### ISSUE THREAD

**Issue by mimon** [troyanskiy/ngx-resource#133]
Thank you for this library. I really liked ng-resource that existed in Angular 1 and I'm exited to explore this Angular 2 version of it.

From the current Readme example:
```
// Creating the news
    let newNews:INews = {
      date: '17.06.2016',
      title: 'The great day',
      text: 'The best day ever',
      fullText: 'Should be full text here';
    }
    // That will execute the POST request to https://domain.net/api/users
    // Expected to receive created news object which will be assigned to newNews
    let newNews = this.newsRes.save(newNews);
```

From this example it seems I have to POST `newNews` on the server in order to instantiate the resource object.

Is there any way I can instantiate a Resource object (with or without model data) without invoking any HTTP?

In Angular 1's $resource one could do
```
ExampleResource = $resource(...)
o = new ExampleResource({ model_fields: .. }) // I can now store and modify data in `o` before I POST/PUT
o.$save() // Results in a HTTP POST

**Comment by troyanskiy** [comment]
Hello @mimon 
Thank you for using the lib
I think you can do that with `model`
Please check doc how to create model and then you can do following
``` typescript
const myModel = this.myResource.$createModel();
myModel.field1 = 'data1';
myModel.$save();
```

**Comment by mimon** [comment]
Thanks. Hm, would it be possible to set data using a JSON or does it have to be field by field ?

**Comment by troyanskiy** [comment]
```typescript
myModel.$setData(yourJsonObject)
```

**Comment by mimon** [comment]
Hm, it seems I have to use `myModel.$resource.$setData(...)` (I'm inheriting `ResourceCRUDBase`). Does that make a difference or is that expected?

**Comment by troyanskiy** [comment]
@mimon did you create your model class like on that example https://github.com/troyanskiy/ngx-resource#example-of-resource-model-usage ?

**Comment by mimon** [comment]
Hm, no I used `ResourceCRUDBase` since I'd like to avoid defining a model on the front-end (which is quite large). I also have the use case that a resource may be identified by multiple primary keys. Eg. `/shops/:shopId/products/:productId`.

So I have
```
interface IQuery {
  shop_id: number;
}

@Injectable()
@ResourceParams({
  url: `/shops/{!shopId}/products/{id}`,
  params: {
    shopId: '@shop_id' // Products has a 'shop_id' field'
  }
})
export class BankAccountService extends ResourceCRUDBase<IQuery, IQuery, any, any> {

}
```

**Comment by troyanskiy** [comment]
@mimon Unfortunately it's possible to have _creation_, `$save()` and etc only by creating Model.
Otherwise, you can only resource methods and work with pure js objects (without `$save()`...)

**Comment by mimon** [comment]
I was having a look in the example you suggested: https://github.com/troyanskiy/ngx-resource#example-of-resource-model-usage and tried to create a test app based on it.

But there seem to be some inconsistency there. It looks like
*  `TestResource` is depending on `TestModel` and vice verse:
* `TestModel` is depending on `TestResource`

Is that an error or is it just me messing something up?

**Comment by troyanskiy** [comment]
Hello all.

I've released some kind of beta of new library which is called `rest-core` + `rest-ngx`.
Please check them [`rest-core`](https://www.npmjs.com/package/rest-core) and [`rest-ngx`](https://www.npmjs.com/package/rest-ngx).

It works the way like `ngx-resource` but has a lot of breaking changes.
Something was removed or simplified.

I've migrated all my projects to the new library.
If you wish to switch to HttpClient or use some other http handlers like `fetch` try to migrate your projects to the lib.

Bugs and help requests are welcome in corresponding repos.

Thanks!

PS: Since `ngx-resource` is no longer supported by me, closing the issue.
