### ISSUE TITLE
Migrating to angular 5?

### ISSUE THREAD

**Issue by RyuuGan** [troyanskiy/ngx-resource#146]
Are you going to migrate to angular 5 due to `Http` from `@angular/http` is deprecated, and need to use `HttpClient` from `@angular/common/http`?

**Comment by troyanskiy** [comment]
Hello.
No, the library is not supported anymore.

Have a look at [rest-core](https://github.com/troyanskiy/rest-core) + [rest-ngx](https://github.com/troyanskiy/rest-ngx)
