### ISSUE TITLE
then is not a function in IResourceMethodPromise

### ISSUE THREAD

**Issue by Komdosh** [troyanskiy/ngx-resource#151]
After update to version 7 code below is not working anymore
```
@Injectable()
@ResourceParams({
  pathPrefix: '/api/user'
})
export class UserResource extends Resource {
  @ResourceAction({
    method: ResourceRequestMethod.Get,
  })
  getUser: IResourceMethodPromise<any, any>;
}
```
after update, I changed IResourceMethod to IResourceMethodPromise

then use it, but `then` is not function occured

```
constructor(private userResource: UserResource){
 this.userResource.getUser().then(u=>console.log(u));
}
```

**Comment by troyanskiy** [comment]
Hello.
By default version 7 returns Observable instead of Promise.
try
```
@ResourceParams({
  pathPrefix: '/api/user'
  returnAs: ResourceActionReturnType.Promise
})
```

Or add somewhere your app.module constructor or in the app.component constructor to set for all your resources to return Promise
```
ResourceGlobalConfig.returnAs = ResourceActionReturnType.Promise
```

**Comment by adrianmarinica** [comment]
I ran into the same issue. Maybe it would be better to mention this somewhere in the documentation.

**Comment by troyanskiy** [comment]
I will create some migration guide.
