### ISSUE TITLE
Promise rejected for resource declared in custom ngModule

### ISSUE THREAD

**Issue by adrianmarinica** [troyanskiy/ngx-resource#159]
After integrating the library and creating all the resources in the main AppModule, I decided to create a separate NgModule specifically for the resources. When doing so, all requests error out with `Error: ResourceHandler is not provided at ResourceHandlerNoop.handle`. 

The resource handler is in fact provided in all resources through the constructor, even though it recently became an optional parameter.

I tried putting the ` imports: [ResourceModule.forRoot()]` in both the AppModule and the custom module, both times the promise got rejected. I also looked over the `forChild` method, but it seems identical to the `forRoot` one. I guess it's provided for backwards compatibility?

Have I stumbled upon a bug, or am I not using things properly?

**Comment by troyanskiy** [comment]
Hello,

You have to import ResourceModule from @ngx-resourse/handler-ngx-http

сб, 24 авг. 2019 г. в 23:02, Adrian Marinica <notifications@github.com>:

**Comment by adrianmarinica** [comment]
Thank you, it worked. Cheers!
