### ISSUE TITLE
Support for Angular 10

### ISSUE THREAD

**Issue by beradrian** [troyanskiy/ngx-resource#171]
After upgrading to Angular 10 I get errors using the latest version of this package.

**Comment by httpete** [comment]
this should be an easy fix 
error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

**Comment by tarlepp** [comment]
any updates with this?

**Comment by troyanskiy** [comment]
Hello @all 
I have just released version 10.0.0 with angular 10 support.
Please let me know if you will have some problems and free to open new issues in that case.
Thank you!

**Comment by tarlepp** [comment]
@troyanskiy thanks a lot, all seems to work as expected.
